language: python
python:
  - '3.6'

install:
  - 'pip install pipenv'
  - 'travis_wait pipenv install pusher'
  - 'pipenv install'

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE DATABASE centauri;" -U postgres

script:
  - chmod u+x release.sh && ./release.sh
  - coverage run --source=authors.apps ./manage.py test --settings=authors.settings
  - coverage report

after_success:
  - coveralls
